models/penilaian_kelas.py
import uuid
from configs.db import db

class PenilaianKelas(db.Model):
    __tablename__ = "penilaian_kelas"

    id = db.Column(db.String, primary_key=True, default=lambda: str(uuid.uuid4()))
    kelas_id = db.Column(db.String, db.ForeignKey("kelas.id"), nullable=False, unique=True)

    # Range Nilai
    nilai_a_min = db.Column(db.Float, nullable=False)
    nilai_b_min = db.Column(db.Float, nullable=False)
    nilai_c_min = db.Column(db.Float, nullable=False)
    nilai_d_min = db.Column(db.Float, nullable=False)
    nilai_e_min = db.Column(db.Float, nullable=False, default=0)

    kelas = db.relationship("Kelas", backref=db.backref("penilaian", uselist=False))

forms/login_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Length

class LoginForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Length(min=3)])
    password = PasswordField("Password", validators=[DataRequired()])
    submit = SubmitField("Login")

forms/penilaian_kelas_form.py
from flask_wtf import FlaskForm
from wtforms import FloatField, SubmitField
from wtforms.validators import DataRequired

class PenilaianKelasForm(FlaskForm):
    nilai_a_min = FloatField("Nilai Minimal A", validators=[DataRequired()])
    nilai_b_min = FloatField("Nilai Minimal B", validators=[DataRequired()])
    nilai_c_min = FloatField("Nilai Minimal C", validators=[DataRequired()])
    nilai_d_min = FloatField("Nilai Minimal D", validators=[DataRequired()])
    nilai_e_min = FloatField("Nilai Minimal E", default=0)

    submit = SubmitField("Simpan Penilaian")

forms/register_form.py
from flask_wtf import FlaskForm
from wtforms import StringField,  PasswordField, SubmitField
from wtforms.validators import DataRequired, Length

class RegisterForm(FlaskForm):
    fullname = StringField("Nama Lengkap", validators=[DataRequired(), Length(min=3)])   
    email = StringField("Email", validators=[DataRequired(), Length(min=3)])
    password = PasswordField("Password", validators=[DataRequired()])
    submit = SubmitField("Daftar")

endpoints/routes.py
import os
import uuid
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_user,current_user,login_required,logout_user
from configs.db import db
from forms.dosen_form import DosenForm
from forms.kelas_form import KelasForm
from forms.kelas_mahasiswa_form import KelasMahasiswaForm
from forms.login_form import LoginForm
from forms.logout_form import LogoutForm
from forms.mahasiswa_form import MahasiswaForm
from forms.matakuliah_form import MataKuliahForm
from forms.materi_form import MateriForm
from forms.penilaian_kelas_form import PenilaianKelasForm
from forms.register_form import RegisterForm
from forms.tugas_form import TugasForm
from forms.tugas_mahasiswa_form import TugasMahasiswaForm
from models.dosen import Dosen
from models.kelas import Kelas
from models.kelas_mahasiswa import KelasMahasiswa
from models.mahasiswa import Mahasiswa
from models.matakuliah import MataKuliah
from models.materi import Materi
from models.penilaian_kelas import PenilaianKelas
from models.tugas import Tugas
from models.tugas_mahasiswa import TugasMahasiswa
from models.user import User

from werkzeug.security import generate_password_hash,check_password_hash

from utils.converter import konversi_nilai_ke_huruf
from utils.generator import generate_unique_username

from sqlalchemy.orm import aliased
from datetime import datetime,timezone

from utils.supabase_client import delete_file_storage_supabase, upload_file_storage_supabase

main_bp = Blueprint("main", __name__)


@main_bp.route("/")
@login_required
def home_view():
    #pada pengembangan versi selanjutnya buatkan form_logout sebagai context global 
    form_logout = LogoutForm()

    # ======================
    # JIKA DOSEN
    # ======================
    if getattr(current_user, "dosen", None):
        dosen = current_user.dosen

        # semua matakuliah milik dosen
        matakuliah = MataKuliah.query.filter_by(
            dosen_id=dosen.id
        ).all()

        # semua kelas dari matakuliah dosen
        kelas = (
            Kelas.query
            .join(MataKuliah)
            .filter(MataKuliah.dosen_id == dosen.id)
            .all()
        )

        return render_template(
            "profil_dosen.html",
            form_logout=form_logout,
            matakuliah=matakuliah,
            kelas=kelas
        )

    # ======================
    # JIKA MAHASISWA
    # ======================
    if getattr(current_user, "mahasiswa", None):

        # semua matakuliah (global)
        matakuliah = MataKuliah.query.all()

        # semua kelas (global)
        kelas = Kelas.query.all()

        return render_template(
            "profil_mahasiswa.html",
            form_logout=form_logout,
            matakuliah=matakuliah,
            kelas=kelas
        )

    # ======================
    # BELUM PUNYA ROLE
    # ======================
    return redirect(url_for("main.register_data_mahasiswa_view"))

@main_bp.route("/join-kelas/<id>")
@login_required
def join_kelas_view(id):
    form_logout = LogoutForm()

    # ======================
    # JIKA DOSEN
    # ======================
    if getattr(current_user, "dosen", None):
        dosen = current_user.dosen

        # ambil kelas berdasarkan slug dan pastikan milik dosen
        kelas = Kelas.query.join(MataKuliah).filter(
            Kelas.id == id,
            MataKuliah.dosen_id == dosen.id
        ).first()

        if not kelas:
            flash("Anda tidak punya hak akses ke kelas ini.", "error")
            return redirect(url_for("main.home_view"))
        
        km = KelasMahasiswa.query.filter_by(
            kelas_id=kelas.id
        ).all()

        penilaian = kelas.penilaian  # PenilaianKelas (boleh None)

        for km_item in km:
            # ambil semua jawaban mahasiswa ini
            jawaban_list = (
                TugasMahasiswa.query
                .join(Tugas)
                .filter(
                    Tugas.kelas_id == kelas.id,
                    TugasMahasiswa.mahasiswa_id == km_item.mahasiswa_id,
                    TugasMahasiswa.nilai.isnot(None)
                )
                .all()
            )

            total_tugas = Tugas.query.filter_by(kelas_id=kelas.id).count()
            total_nilai = sum(j.nilai for j in jawaban_list)

            if total_tugas > 0:
                rata_nilai = total_nilai / total_tugas
            else:
                rata_nilai = 0

            km_item.rata_nilai = round(rata_nilai, 2)
            km_item.nilai_huruf = konversi_nilai_ke_huruf(rata_nilai, penilaian)

        form_kelas_mahasiswa = KelasMahasiswaForm()
        form_tugas= TugasForm()
        tugas_kelas = Tugas.query.filter_by(kelas_id = kelas.id).all()

        form_materi= MateriForm()
        materi_kelas = Materi.query.filter_by(kelas_id = kelas.id).all()
      
        return render_template(
            "join_kelas_dosen.html",
            form_logout=form_logout,
            kelas=kelas,
            kelas_mahasiswa = km,
            tugas_kelas = tugas_kelas,
            kelas_mahasiswa_form = form_kelas_mahasiswa,
            form_tugas=form_tugas,
            form_materi=form_materi,
            materi_kelas=materi_kelas
        )

    # ======================
    # JIKA MAHASISWA
    # ======================
    if getattr(current_user, "mahasiswa", None):
        mahasiswa = current_user.mahasiswa

        # ambil kelas berdasarkan slug
        kelas = Kelas.query.filter_by(id=id).first()
        if not kelas:
            flash("Kelas tidak ditemukan.", "error")
            return redirect(url_for("main.home_view"))

        # cek apakah mahasiswa sudah terdaftar di kelas
        km = KelasMahasiswa.query.filter_by(
            kelas_id=kelas.id,
            mahasiswa_id=mahasiswa.id
        ).first()

        if not km:
            # otomatis tambah mahasiswa ke kelas
            km = KelasMahasiswa(kelas_id=kelas.id, mahasiswa_id=mahasiswa.id)
            db.session.add(km)
            db.session.commit()
            flash(f"Anda berhasil bergabung di {kelas.nama}", "success")
        else:
            flash(f"Anda sudah terdaftar di {kelas.nama}", "info")
        
        Jawaban = aliased(TugasMahasiswa)

        tugas_kelas = (
            db.session.query(Tugas, Jawaban)
            .outerjoin(
                Jawaban,
                (Jawaban.tugas_id == Tugas.id) &
                (Jawaban.mahasiswa_id == mahasiswa.id)
            )
            .filter(Tugas.kelas_id == kelas.id)
            .all()
        )

        total_tugas = len(tugas_kelas)

        total_nilai = sum(
            jawaban.nilai
            for _, jawaban in tugas_kelas
            if jawaban and jawaban.nilai is not None
        )

        if total_tugas > 0:
            rata_nilai = total_nilai / total_tugas
        else:
            rata_nilai = 0

        penilaian = kelas.penilaian

        nilai_huruf_ipk = konversi_nilai_ke_huruf(
            rata_nilai,
            penilaian
)
        form_tugas = TugasMahasiswaForm()
        materi_kelas = Materi.query.filter_by(kelas_id = kelas.id).all()

        return render_template(
            "join_kelas_mahasiswa.html",
            form_logout=form_logout,
            kelas=kelas,
            tugas_kelas = tugas_kelas,
            nilai_ipk_kelas=round(rata_nilai, 2),
            nilai_huruf_ipk=nilai_huruf_ipk,
            form_tugas = form_tugas,
            materi_kelas=materi_kelas,
            tanggal_hari_ini=datetime.now(timezone.utc).replace(tzinfo=None)
        )

    # ======================
    # BELUM PUNYA ROLE
    # ======================
    return redirect(url_for("main.register_data_mahasiswa_view"))

@main_bp.route("/kelas-mahasiswa-update", methods=["POST"])
@login_required
def kelas_mahasiswa_update():
    form = KelasMahasiswaForm()

    # ==========================
    # CEK ROLE DOSEN
    # ==========================
    dosen = getattr(current_user, "dosen", None)
    if not dosen:
        flash("Akses ditolak", "error")
        return redirect(url_for("main.home_view"))

    # ==========================
    # VALIDASI FORM
    # ==========================
    if not form.validate_on_submit():
        flash("Data tidak valid", "error")
        return redirect(request.referrer)

    try:
        kelas_mahasiswa_id = request.form.get("kelas_mahasiswa_id")

        km = KelasMahasiswa.query.get(kelas_mahasiswa_id)
        if not km:
            flash("Data kelas mahasiswa tidak ditemukan", "error")
            return redirect(request.referrer)

        # ==========================
        # CEK KEPEMILIKAN KELAS
        # ==========================
        if km.kelas.matakuliah.dosen_id != dosen.id:
            flash("Anda tidak berhak mengubah data ini", "error")
            return redirect(url_for("main.home_view"))

        # ==========================
        # UPDATE DATA
        # ==========================
        km.nilai_akhir = form.nilai_akhir.data
        km.status = "Selesai"

        db.session.commit()
        flash("Data mahasiswa berhasil diperbarui", "success")

    except Exception as e:
        db.session.rollback()
        flash("Terjadi kesalahan saat update data", "error")
        print(e)

    return redirect(request.referrer)

@main_bp.route("/login", methods=["GET", "POST"])
def login_view():
    if current_user.is_authenticated:
        # Redirect sesuai role
        if hasattr(current_user, "dosen") and current_user.dosen:
            return redirect(url_for("main.home_view"))
        elif hasattr(current_user, "mahasiswa") and current_user.mahasiswa:
            return redirect(url_for("main.home_view"))
        else:
            return redirect(url_for("main.register_data_mahasiswa_view"))
        
    form = LoginForm()

    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data

        user = User.query.filter_by(email=email).first()
        if not user:

templates/layout.html
<!doctype html>
<html>

<head>
	 <meta name="viewport" content="width=device-width, initial-scale=1" />
	{% block head %}
	<script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
	<script defer src="https://cdn.jsdelivr.net/npm/@alpinejs/focus@3.x.x/dist/cdn.min.js"></script>
	<script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>

	<title>{% block title %}{% endblock %} - Elearning</title>

	{% endblock %}
</head>

<body class="flex flex-col gap-4">
	<header class="sticky top-0 z-10 bg-neutral-50">
		<nav x-data="{ mobileMenuIsOpen: false }" x-on:click.away="mobileMenuIsOpen = false"
			class="flex items-center justify-between border-b border-neutral-300 px-6 py-4 dark:border-neutral-700 "
			aria-label="penguin ui menu">

			<div class="text-2xl font-bold">
				<a href="{{ url_for('main.home_view') }}">
					<span>PROYEK E-<span class="">Learning</span>
						<!-- <img src="./logo.svg" alt="brand logo" class="w-10" /> -->
				</a>
			</div>

			{% if current_user.is_authenticated %}
			<ul class="items-center gap-4 md:flex">
				<li>
					<form action="{{ url_for('main.logout_view') }}" method="POST"
						class="font-medium">

						{{ form_logout.hidden_tag() }}
						{{ form_logout.submit(class="cursor-pointer") }}

					</form>
				</li>
			</ul>
			{% else %}
			<ul class="items-center gap-4 md:flex">
				<li>
					<a href="{{ url_for('main.login_view') }}"
						class="font-medium text-neutral-600 hover:text-black dark:text-neutral-300 dark:hover:text-white">
						Login
					</a>
				</li>
			</ul>
			{% endif %}

		</nav>
	</header>
	<div id="content">{% block content %}{% endblock %}</div>

	<div class="p-4">
		{% block footer %}
		&copy; 2025 - PROYEK ELEARNING
		{% endblock %}
	</div>
</body>

</html>

templates/login.html
<!DOCTYPE html>
<html lang="en" class="h-full">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block head %}
  <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
  <script defer src="https://cdn.jsdelivr.net/npm/@alpinejs/focus@3.x.x/dist/cdn.min.js"></script>
  <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
  <!--<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">-->
  <title>Autentikasi - Elearning</title>

  {% endblock %}
</head>

<body class="bg-gradient-to-br from-blue-100 to-purple-100 flex items-center justify-center h-screen">

  <div class="bg-white shadow-xl rounded-2xl p-10 max-w-md w-full">
     <h1 class="text-3xl font-bold mb-4">Proyek Elearning</h1>
    <div class="mb-4 font-bold text-xl text-center">
      Login
    </div>


    <form method="POST" action="{{ url_for('main.login_view') }}">
      {{ form.hidden_tag() }} <!-- CSRF TOKEN -->
      
      <!-- Tampilkan flash message -->
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      <div class="mb-4">
        {% for category, message in messages %}
        <div class="px-4 py-2 rounded mb-2
                        {% if category == 'success' %} bg-green-100 text-green-700
                        {% elif category == 'error' %} bg-red-100 text-red-700
                        {% elif category == 'warning' %} bg-yellow-100 text-yellow-700
                        {% else %} bg-gray-100 text-gray-700 {% endif %}">
          {{ message }}
        </div>
        {% endfor %}
      </div>
      {% endif %}
      {% endwith %}

      <div class="mb-4">
        {{ form.email.label(class="block text-gray-700 mb-2") }}
        {{ form.email(class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2
        focus:ring-blue-500") }}
        {% if form.email.errors %}
        <ul class="text-red-500 text-sm mt-1">
          {% for error in form.email.errors %}
          <li>{{ error }}</li>
          {% endfor %}
        </ul>
        {% endif %}
      </div>

      <div class="mb-1">
        {{ form.password.label(class="block text-gray-700 mb-2") }}
        {{ form.password(class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2
        focus:ring-blue-500") }}

      </div>
      <div class="mb-4">
        <a class="underline" href="#">Lupa Sandi</a>
      </div>

      <button type="submit"
        class="w-full cursor-pointer bg-blue-600 text-white py-2 rounded-lg hover:bg-blue-700 transition-colors">
        Masuk
      </button>
    </form>
    <div class="my-4">
      Belum punya akun? <a class="underline" href="{{ url_for('main.register_view') }}">Daftar</a>
    </div>

    <div class="flex gap-4 mt-4 ">
      <a class="underline" href="{{ url_for('main.about_view') }}">Tentang Kami</a>
      <a class="underline" href="{{ url_for('main.tos_view') }}" >Syarat dan ketentuan</a>
    </div>
  </div>

</body>

</html>

templates/page.html
{% extends "layout.html" %}
{% block title %}About{% endblock %}

{% block content %}
  <h1>Page</h1>
 
{% endblock %}

templates/profil_dosen.html
{% extends "layout.html" %}
{% block title %}Profil{% endblock %}

{% block content %}
<div
    class="group flex rounded-sm w-full flex-col overflow-hidden border border-neutral-300 bg-neutral-50 text-neutral-600 dark:border-neutral-700 dark:bg-neutral-900 dark:text-neutral-300">
  
    <div class="relative h-36">
        <div class="h-full w-full bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500"></div>
        <div
            class="relative z-10 mx-auto -mt-14 size-28 overflow-hidden rounded-full border-4 border-neutral-50 dark:border-neutral-900">
              <img src="{{ url_for('static', filename='images/person.png') }}"
                class="h-full object-cover transition duration-700 ease-out group-hover:scale-105" alt="avatar" />
        </div>
    </div>
    <!-- Body -->
    <div class="flex flex-col gap-2 p-6 text-center mt-12">
        <h3 class="text-balance text-xl font-bold text-neutral-900 lg:text-2xl dark:text-white"
            aria-describedby="profileDescription">{{current_user.fullname}}</h3>
        <span
            class="mx-auto w-fit bg-black px-2 py-1 text-xs text-neutral-100 dark:bg-white dark:text-black rounded-sm">DOSEN</span>

    </div>
</div>

 
 <!-- Tampilkan flash message -->
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      <div class="m-4 ">
        {% for category, message in messages %}
        <div class="px-4 py-2 rounded mb-2
                        {% if category == 'success' %} bg-green-100 text-green-700
                        {% elif category == 'error' %} bg-red-100 text-red-700
                        {% elif category == 'warning' %} bg-yellow-100 text-yellow-700
                        {% else %} bg-gray-100 text-gray-700 {% endif %}">
          {{ message }}
        </div>
        {% endfor %}
      </div>
      {% endif %}
      {% endwith %}

<div class="px-4 flex flex-col md:flex-row gap-4 my-4">
    <div class="w-full md:w-1/2">
        <div class="flex justify-between gap-4 bg-green-300 p-4">
            <h3 class="font-bold">Mata Kuliah Saya</h3>
            <a class="underline" href="{{ url_for('main.add_matakuliah_view') }}">Tambah Matakuliah</a>
        </div>

        <ul class="bg-green-100 p-4">
            {% for mk in matakuliah %}
            <li>{{ mk.kode }} - {{ mk.nama }} </li>
            {% endfor %}
        </ul>
    </div>
    <div class="w-full md:w-1/2">
        <div class="flex justify-between gap-4 bg-red-300 p-4">
            <h3 class="font-bold">Kelas Saya</h3>
            <a class="underline" href="{{ url_for('main.add_kelas_view') }}">Tambah Kelas</a>
        </div>

        <ul class="bg-red-100 p-4">
            {% for k in kelas %}
            <li>
                <div class="flex gap-4 justify-between mb-4">
                    <span> {{ k.nama }} | {{ k.matakuliah.nama }} | {{ k.semester }} | {{ k.tahun_ajaran }}</span>
                    <a class="underline" href="{{ url_for('main.join_kelas_view', id=k.id) }}">Join Kelas</a>
                </div>
               
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

templates/profil_mahasiswa.html
{% extends "layout.html" %}
{% block title %}Profil{% endblock %}

{% block content %}
<div
    class="group flex rounded-sm w-full flex-col overflow-hidden border border-neutral-300 bg-neutral-50 text-neutral-600 dark:border-neutral-700 dark:bg-neutral-900 dark:text-neutral-300">
 
    <div class="relative h-36">
            <div class="h-full w-full bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500"></div>
        <div
            class="relative z-10 mx-auto -mt-14 size-28 overflow-hidden rounded-full border-4 border-neutral-50 dark:border-neutral-900">
               <img src="{{ url_for('static', filename='images/person.png') }}"
                class="h-full object-cover transition duration-700 ease-out group-hover:scale-105" alt="avatar" />
        </div>
    </div>
    <!-- Body -->
    <div class="flex flex-col gap-2 p-6 text-center mt-12">
        <h3 class="text-balance text-xl font-bold text-neutral-900 lg:text-2xl dark:text-white"
            aria-describedby="profileDescription">{{current_user.fullname}}</h3>
        <span
            class="mx-auto w-fit bg-black px-2 py-1 text-xs text-neutral-100 dark:bg-white dark:text-black rounded-sm">MAHASISWA</span>

    </div>
</div>


<!-- Tampilkan flash message -->
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div class="m-4">
    {% for category, message in messages %}
    <div class="px-4 py-2 rounded mb-2
                        {% if category == 'success' %} bg-green-100 text-green-700
                        {% elif category == 'error' %} bg-red-100 text-red-700
                        {% elif category == 'warning' %} bg-yellow-100 text-yellow-700
                        {% else %} bg-gray-100 text-gray-700 {% endif %}">
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}
{% endwith %}

<div class="px-4 flex flex-col md:flex-row gap-4 my-4">
  
    <div class="w-full ">
        <div class="bg-green-300 p-4">
            <h3 class="font-bold">Kelas Online</h3>         
        </div>

        <ul class="bg-green-100 p-4">
            {% for k in kelas %}
            <li class="flex gap-4 justify-between mb-4">
                <span>{{ k.nama }} | {{ k.matakuliah.nama }} | {{ k.matakuliah.dosen.user.fullname }} | {{ k.semester }} | {{ k.tahun_ajaran }}</span>
                <a class="underline" href="{{ url_for('main.join_kelas_view', id=k.id) }}">Join Kelas</a>

            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

templates/register.html
<!DOCTYPE html>
<html lang="en" x-data="{ tab: 'login' }" class="h-full">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block head %}
  <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
  <script defer src="https://cdn.jsdelivr.net/npm/@alpinejs/focus@3.x.x/dist/cdn.min.js"></script>
  <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
  <!--<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">-->
  <title>Autentikasi - Elearning</title>

  {% endblock %}
</head>

<body class="bg-gradient-to-br from-blue-100 to-purple-100 flex items-center justify-center h-screen">

  <div class="bg-white shadow-xl rounded-2xl p-10 max-w-md w-full">
    <h1 class="text-3xl font-bold mb-4">Proyek Elearning</h1>
    <div class="mb-4 font-bold text-xl text-center">
      Registrasi
    </div>


    <form method="POST" action="{{ url_for('main.register_view') }}">
      {{ form.hidden_tag() }} <!-- CSRF TOKEN -->
      
 <!-- Tampilkan flash message -->
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      <div class="mb-4">
        {% for category, message in messages %}
        <div class="px-4 py-2 rounded mb-2
                        {% if category == 'success' %} bg-green-100 text-green-700
                        {% elif category == 'error' %} bg-red-100 text-red-700
                        {% elif category == 'warning' %} bg-yellow-100 text-yellow-700
                        {% else %} bg-gray-100 text-gray-700 {% endif %}">
          {{ message }}
        </div>
        {% endfor %}
      </div>
      {% endif %}
      {% endwith %}

      <div class="mb-4">
        {{ form.fullname.label(class="block text-gray-700 mb-2") }}
        {{ form.fullname(class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2
        focus:ring-blue-500") }}
      </div>
      <div class="mb-4">
        {{ form.email.label(class="block text-gray-700 mb-2") }}
        {{ form.email(class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2
        focus:ring-blue-500") }}
      </div>

      <div class="mb-4">
        {{ form.password.label(class="block text-gray-700 mb-2") }}
        {{ form.password(class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2
        focus:ring-blue-500") }}
      </div>
   
      <button type="submit"
        class="w-full cursor-pointer bg-blue-600 text-white py-2 rounded-lg hover:bg-blue-700 transition-colors">
        Daftar
      </button>
    </form>
    <div class="my-4">
      Sudah punya akun? <a class="underline" href="{{ url_for('main.login_view') }}">Masuk</a>
    </div>
   
    <div class="flex gap-4 mt-4 ">
       <a class="underline" href="{{ url_for('main.about_view') }}">Tentang Kami</a>
      <a class="underline" href="{{ url_for('main.tos_view') }}" >Syarat dan ketentuan</a>
    </div>
  </div>

</body>

</html>